import type { SignalFeedItem, Project, ProjectThought } from './types';

const now = Date.now();
const hour = 3600000;
const day = 86400000;

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'mock-proj-1',
    name: 'Agent Architectures',
    description: 'Multi-agent coordination patterns, memory systems, orchestration',
    layer: 'strategic',
    created_at: new Date(now - 7 * day).toISOString(),
    updated_at: new Date(now - 1 * hour).toISOString(),
  },
  {
    id: 'mock-proj-2',
    name: 'Signal Capture v2',
    description: 'Enrichment pipeline, project linking, export improvements',
    layer: 'tactical',
    created_at: new Date(now - 3 * day).toISOString(),
    updated_at: new Date(now - 2 * hour).toISOString(),
  },
  {
    id: 'mock-proj-3',
    name: 'Quantum Computing Reading',
    description: null,
    layer: 'hibernating',
    created_at: new Date(now - 14 * day).toISOString(),
    updated_at: new Date(now - 10 * day).toISOString(),
  },
];

export const MOCK_THOUGHTS: ProjectThought[] = [
  {
    id: 'mock-thought-1',
    project_id: 'mock-proj-1',
    content: 'Cursor experiment confirms hierarchical orchestration beats flat swarms at scale — need to map this against MAST taxonomy failure modes',
    created_at: new Date(now - 1 * hour).toISOString(),
    updated_at: new Date(now - 1 * hour).toISOString(),
  },
  {
    id: 'mock-thought-2',
    project_id: 'mock-proj-1',
    content: 'Ralph Loop memory architecture is promising for agent persistence. Key insight: separate raw logs from curated knowledge, automate consolidation.',
    created_at: new Date(now - 1 * day).toISOString(),
    updated_at: new Date(now - 1 * day).toISOString(),
  },
  {
    id: 'mock-thought-3',
    project_id: 'mock-proj-1',
    content: 'World models vs word models framing crystallizes the core limitation — current architectures optimize for token prediction, not strategic reasoning. Need new primitives.',
    created_at: new Date(now - 3 * day).toISOString(),
    updated_at: new Date(now - 3 * day).toISOString(),
  },
  {
    id: 'mock-thought-4',
    project_id: 'mock-proj-2',
    content: 'Projects feature scoped — 3 layers (tactical/strategic/hibernating), freeform thoughts as primary content, post-capture signal linking.',
    created_at: new Date(now - 2 * hour).toISOString(),
    updated_at: new Date(now - 2 * hour).toISOString(),
  },
  {
    id: 'mock-thought-5',
    project_id: 'mock-proj-2',
    content: 'CaptureForm stays untouched — linking happens from project detail page or signal detail page. No capture-time friction.',
    created_at: new Date(now - 1 * day).toISOString(),
    updated_at: new Date(now - 1 * day).toISOString(),
  },
];

export const MOCK_SIGNALS: SignalFeedItem[] = [
  {
    id: 'mock-1',
    created_at: new Date(now - 2 * 60000).toISOString(),
    source_url: 'https://cursor.com/blog/browser-agents',
    raw_input: 'Cursor browser-building multi-agent experiment — flat swarm failed at scale, hierarchical orchestration resolved lock contention',
    capture_context: 'relates to backpressure pattern from Yegge podcast',
    input_method: 'text',
    processing_status: 'pending',
    processed_at: null,
    fetched_title: null,
    is_starred: false,
    is_archived: false,
    is_published: false,
    published_at: null,
    project_id: 'mock-proj-1',
    project_name: 'Agent Architectures',
    source_title: null,
    key_claims: null,
    novelty_assessment: null,
    domain_tags: null,
    signal_type: null,
    source_tier: null,
    frontier_status: null,
    confidence: null,
    cross_signal_notes: null,
    human_note: null,
    human_rating: null,
    tier_override: null,
  },
  {
    id: 'mock-2',
    created_at: new Date(now - 1 * hour).toISOString(),
    source_url: null,
    raw_input: 'Ralph Loop session memory architecture — persistent context across agent restarts via workspace files',
    capture_context: null,
    input_method: 'voice',
    processing_status: 'complete',
    processed_at: new Date(now - 30 * 60000).toISOString(),
    fetched_title: null,
    is_starred: true,
    is_archived: false,
    is_published: true,
    published_at: new Date(now - 30 * 60000).toISOString(),
    project_id: 'mock-proj-1',
    project_name: 'Agent Architectures',
    source_title: 'Ralph Loop: Session Memory Architecture',
    key_claims: [
      'Workspace files provide persistent context across agent session restarts',
      'Memory files split into daily logs vs curated long-term knowledge',
      'Heartbeat-based maintenance enables background memory consolidation',
      'Git-backed memory tracking enables auditable memory evolution',
    ],
    novelty_assessment: 'First documented architecture for agent memory that separates raw logs from curated knowledge with automated consolidation.',
    domain_tags: ['memory-architecture', 'agent-persistence', 'workspace-design'],
    signal_type: 'architectural_pattern',
    source_tier: 'practitioner',
    frontier_status: 'achievable_now',
    confidence: 0.75,
    cross_signal_notes: 'Connects to OpenClaw memory system design. Similar pattern to human note-taking workflows (daily journal → periodic review → long-term memory).',
    human_note: null,
    human_rating: null,
    tier_override: null,
  },
  {
    id: 'mock-3',
    created_at: new Date(now - 3 * hour).toISOString(),
    source_url: 'https://arxiv.org/abs/2503.13657',
    raw_input: 'MAST taxonomy for multi-agent failure modes — systematic classification of coordination failures',
    capture_context: 'need to cross-reference with Cursor experiment results',
    input_method: 'text',
    processing_status: 'processing',
    processed_at: null,
    fetched_title: null,
    is_starred: false,
    is_archived: false,
    is_published: false,
    published_at: null,
    project_id: null,
    project_name: null,
    source_title: null,
    key_claims: null,
    novelty_assessment: null,
    domain_tags: null,
    signal_type: null,
    source_tier: null,
    frontier_status: null,
    confidence: null,
    cross_signal_notes: null,
    human_note: null,
    human_rating: null,
    tier_override: null,
  },
  {
    id: 'mock-4',
    created_at: new Date(now - 1 * day).toISOString(),
    source_url: null,
    raw_input: 'bash outperforms MCP for agent tool use but can\'t clear enterprise procurement — interesting tension between technical superiority and adoption pathway',
    capture_context: null,
    input_method: 'text',
    processing_status: 'dismissed',
    processed_at: new Date(now - 20 * hour).toISOString(),
    fetched_title: null,
    is_starred: false,
    is_archived: true,
    is_published: false,
    published_at: null,
    project_id: null,
    project_name: null,
    source_title: null,
    key_claims: null,
    novelty_assessment: null,
    domain_tags: null,
    signal_type: null,
    source_tier: null,
    frontier_status: null,
    confidence: null,
    cross_signal_notes: null,
    human_note: null,
    human_rating: null,
    tier_override: null,
  },
  {
    id: 'mock-5',
    created_at: new Date(now - 2 * day).toISOString(),
    source_url: 'https://latent.space/p/world-models-word-models',
    raw_input: 'Experts have world models, LLMs have word models — framing the architecture gap',
    capture_context: 'convergence with Logan Graham Anthropic tweet about agent economy',
    input_method: 'share',
    processing_status: 'complete',
    processed_at: new Date(now - 1.5 * day).toISOString(),
    fetched_title: null,
    is_starred: true,
    is_archived: false,
    is_published: true,
    published_at: new Date(now - 1.5 * day).toISOString(),
    project_id: null,
    project_name: null,
    source_title: 'World Models vs Word Models: The Architecture Gap',
    key_claims: [
      'LLMs generate probable next tokens (word models) but lack strategic reasoning about other agents and hidden state (world models)',
      'Expert work requires dynamic decision-making considering multi-agent environments',
      'Current architecture defaults to single-shot artifact generation',
    ],
    novelty_assessment: 'Frames the fundamental agent limitation as architectural, not scaling — need new architectures (Context Graphs, RLMs) rather than bigger models.',
    domain_tags: ['world-models', 'architecture-gap', 'agent-limitations', 'strategic-reasoning'],
    signal_type: 'conceptual_framework',
    source_tier: 'field_leader',
    frontier_status: 'still_challenging',
    confidence: 0.85,
    cross_signal_notes: 'Cross-signal convergence: Twitter (Logan Graham, Anthropic) + Email (Latent.Space/swyx) arriving at same limitation from different angles.',
    human_note: null,
    human_rating: 4,
    tier_override: null,
  },
  {
    id: 'mock-6',
    created_at: new Date(now - 3 * day).toISOString(),
    source_url: null,
    raw_input: 'Monty sandbox — Pydantic creator building Python interpreter in Rust for microsecond LLM code execution sandboxing',
    capture_context: 'could obsolete E2B and Modal for simple execution',
    input_method: 'text',
    processing_status: 'complete',
    processed_at: new Date(now - 2.5 * day).toISOString(),
    fetched_title: null,
    is_starred: false,
    is_archived: false,
    is_published: false,
    published_at: null,
    project_id: null,
    project_name: null,
    source_title: 'Monty: Rust-Based Python Sandbox for LLM Code Execution',
    key_claims: [
      'Microsecond startup vs seconds for traditional Python interpreters',
      'Built by Pydantic creator Samuel Colvin',
      'Targets LLM code execution sandboxing specifically',
    ],
    novelty_assessment: 'Potential paradigm shift in sandbox economics — if execution is microseconds, the business model changes fundamentally.',
    domain_tags: ['sandboxing', 'rust-python', 'llm-execution'],
    signal_type: 'tooling_evolution',
    source_tier: 'trend_setter',
    frontier_status: 'upcoming_2026',
    confidence: 0.65,
    cross_signal_notes: null,
    human_note: null,
    human_rating: null,
    tier_override: null,
  },
];
